while True:
    
    print("   WELCOME TO MADLIBS!")
    print("-------------------------")
    print("Choose a Madlib :")
    print("   [A] Cafeteria")
    print("   [B] How They Met")
    print("   [C] Cold November Day")

    choice = ""
    while choice not in ["A", "B", "C"]:
        choice = input("   >> ").upper()

    print("\n"*2)

    if choice == "A":
        adj1 = input("Enter an adjective: ")
        adj2 = input("Enter an adjective: ")
        adj3 = input("Enter an adjective: ")
        adj4 = input("Enter an adjective: ")
        verb1 = input("Enter a verb: ")
        verb2 = input("Enter a verb: ")
        noun1 = input("Enter a noun: ")
        noun2 = input("Enter a noun: ")
        noun3 = input("Enter a noun: ")
        noun4 = input("Enter a noun: ")
        print("\n")
        print(f"Our school cafeteria has really {adj1} food. Just\nthinking about it makes my stomach {verb1}. The\nspaghetti is {adj2} and tastes like {noun1}. One\nday, I swear one of my meatballs started to {verb2}! The\nturkey tacos are totally {adj3} and look kind of like old\n{noun2}. My friend Dana actually likes the meatloaf, even\nthough it's {adj3} and {adj4}. I call it \"mystery\nmeatloaf\" and think it's really made out of {noun3}. My\ndad said he'd make my lunches, but the first day, he made me\na sandwich out of {noun4} and peanut butter! I think I'd\nrather take my chances with the cafeteria!")

    elif choice == "B":
        groom = input("Enter the groom's name: ")
        bride = input("Enter the bride's name: ")
        noun1 = input("Enter a noun: ")
        noun2 = input("Enter a noun: ")
        noun3 = input("Enter a noun: ")
        noun4 = input("Enter a noun: ")
        nums1 = input("Enter a number: ")
        nums2 = input("Enter a number: ")
        nums3 = input("Enter a number: ")
        nums4 = input("Enter a number: ")
        school = input("Enter a school name: ")
        place_campus = input("Enter a place on campus: ")
        verb_ing1 = input("Enter a verb (ing): ")
        verb_ing2 = input("Enter a verb (ing): ")
        verb_ing3 = input("Enter a verb (ing): ")
        verb_ed1 = input("Enter a verb (ed): ")
        verb_ed2 = input("Enter a verb (ed): ")
        verb_ed3 = input("Enter a verb (ed): ")
        verb_ed4 = input("Enter a verb (ed): ")
        greeting = input("Enter a greeting: ")
        adj1 = input("Enter an adjective: ")
        adj2 = input("Enter an adjective: ")
        adverb1 = input("Enter an adverb: ")
        adverb2 = input("Enter an adverb: ")
        pnoun1 = input("Enter a plural noun: ")
        pnoun2 = input("Enter a plural noun: ")
        fancy_restau = input("Enter a fancy restaurant: ")
        special_event = input("Enter a special event: ")

        print("\n")
        print(f"When {groom} met {bride}, it was {noun1} at {nums1} sight.")
        print(f"He saw her at {school} High School as she was")
        print(f"standing next to the {place_campus}, {verb_ing1} to another friend")
        print(f"of his. He {verb_ed1} over to say {greeting}, introduced himself,")
        print(f"and asked her name. She was so {adj1}! \"Hi there!\", she said,")
        print(f"{adverb1}, my name is {bride}. She had seen him around")
        print(f"and thought he was super {adj2}. They {verb_ed2} for a")
        print(f"while and then exchanged {pnoun1}. Later, he {verb_ed3} to")
        print(f"as her out on a {noun2}. On their {nums2} date, they")
        print(f"went {verb_ing2} and had {pnoun2} of fun. The {nums3}")
        print(f"time the {verb_ed4} out, he took her to {fancy_restau}. Since")
        print(f"things went so {adverb2} on their {nums4} date he invited")
        print(f"her to his {special_event}. After that, they were officially a")
        print(f"{noun3} and he started {verb_ing3} her as his \"{noun4}\"")

    elif choice == "C":
        adj1 = input("Enter an adjective: ")
        adj2 = input("Enter an adjective: ")
        bird = input("Enter a bird: ")
        room = input("Enter a room in a house: ")
        verb_ed1 = input("Enter a verb (ed): ")
        verb1 = input("Enter a verb: ")
        name = input("Enter a relative's name: ")
        noun1 = input("Enter a noun: ")
        noun2 = input("Enter a noun: ")
        liquid = input("Enter a liquid: ")
        verb_ing1 = input("Enter a verb (ing): ")
        verb_ing2 = input("Enter a verb (ing): ")
        bodypart = input("Enter a body part (plural): ")
        pnoun1 = input("Enter a plural noun: ")

        print("\n"*2)
        print(f"It was a {adj1}, cold November day. I")
        print(f"woke up to the {adj2} smell of {bird}")
        print(f"roasting in the {room} downstairs. I")
        print(f"{verb_ed1} down the stairs to see if I could")
        print(f"help {verb1} the dinner. My mom said,")
        print(f"\"See if {name} needs a fresh {noun1}.\" So I")
        print(f"carried a tray of glasses full of {liquid} into")
        print(f"the {verb_ing1} room. When I got there, I")
        print(f"couldn't believe my {bodypart}! There were")
        print(f"{pnoun1} {verb_ing2} on the {noun2}!")

    print()

    again = input("Would you like to try again? [Y/N] : ")[0].upper()
    if again == "N":
        print()
        print("-------------------------")
        print("   THANKS FOR PLAYING")
        print("-------------------------")
        break
